language: go
go:
      - 1.5.2

before_install:
      - go get github.com/axw/gocov/gocov
      - go get github.com/mattn/goveralls
      - go get golang.org/x/tools/cmd/cover
      - wget https://github.com/ctessum/inmap/releases/download/v1.1.0/testdata_dev.zip
      - unzip testdata_dev.zip

install:
      - go get -d -t ./...

script:
      - go test ./...
      - bash ./.travis/test_coverage.sh
