# InMAPData is the path to location of baseline meteorology and pollutant data.
# The path can include environment variables.
InMAPData = "${evaldata}/InMAPData_v1.2.0.ncf"

# VariableGridData is the path to the location of the variable-resolution gridded
# InMAP data, or the location where it should be created if it doesn't already
# exist. The path can include environment variables.
VariableGridData = "${evaldata}/InMAPData_v1.6.1.gob"

# EmissionsShapefiles are the paths to any emissions shapefiles.
# Can be elevated or ground level; elevated files need to have columns
# labeled "height", "diam", "temp", and "velocity" containing stack
# information in units of m, m, K, and m/s, respectively.
# Emissions will be allocated from the geometries in the shape file
# to the InMAP computational grid, but the mapping projection of the
# shapefile must be the same as the projection InMAP uses.
# Can include environment variables.
EmissionsShapefiles = [
	"${evaldata}/2005_emissions/bioFireEmis.shp",
	"${evaldata}/2005_emissions/Elevated.shp",
	"${evaldata}/2005_emissions/GroundLevel.shp"
]

# EmissionUnits gives the units that the input emissions are in.
# Acceptable values are 'tons/year' and 'kg/year'.
EmissionUnits = "tons/year"

# HTTPAddress is the address for hosting the HTML user interface.
# If HTTPAddress is `:8080`, then the GUI
# would be viewed by visiting `localhost:8080` in a web browser.
# If HTTPport is "", then the web server doesn't run.
HTTPAddress = ":8080"

# OutputFile specifies the path to the desired output shapefile location. It can
# include environment variables.
OutputFile = "nei2005/2005nei_output_${InMAPRunType}.shp"

# LogFile specifies the path to the desired logfile location. It can include
# environment variables. If LogFile is left blank, the logfile will be saved in
# the same location as the OutputFile.
LogFile = "nei2005/logfile_${InMAPRunType}.log"

# OutputVariables specifies which model variables should be included in the
# output file. Each output variable is defined by the desired name and an
# expression that can be used to calculate it
# (in the form VariableName = "Expression"). These expressions can utilize
# variables built into the model, user-defined variables, and functions.
# Available functions include:
# 'exp(x)' which applies the exponetional function e^x.
# 'log(x)' which applies the natural logarithm function log(e).
# 'log10(x)' which applies the base-10 logarithm function log10(e).
# Note: Environment variables can be used in both variable names and expressions.
[OutputVariables]
TotalPM25 = "PrimaryPM25 + pNH4 + pSO4 + pNO3 + SOA"
TotalPopD = "(exp(log(1.078)/10 * TotalPM25) - 1) * TotalPop * allcause / 100000"
WhitNoLatD = "(exp(log(1.078)/10 * TotalPM25) - 1) * WhiteNoLat * allcause / 100000"
BlackD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Black * allcause / 100000"
NativeD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Native * allcause / 100000"
AsianD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Asian * allcause / 100000"
LatinoD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Latino * allcause / 100000"
TotalPop = "TotalPop"
PrimPM25 = "PrimaryPM25"
PSO4 = "pSO4"
PNO3 = "pNO3"
PNH4 = "pNH4"
SOA = "SOA"
SOx = "SOx"
NH3 = "NH3"
NOx = "NOx"
BasePM25 = "BaselineTotalPM25"
WindSpeed = "WindSpeed"

# VarGrid provides information for specifying the variable resolution grid.
[VarGrid]

# VariableGridXo and VariableGridYo are the X and Y coordinates of the
# lower-left corner of the InMAP grid.
VariableGridXo= -2736000.0
VariableGridYo= -2088000.0

# VariableGridDx and VariableGridDy are the X and Y edge lengths of grid
# cells in the outermost nest, in meters.
VariableGridDx= 288000.0
VariableGridDy= 288000.0

# Xnests and Ynests specify nesting multiples in the X and Y directions.
# For instance, if Xnests and Ynests are both [100, 2, 2, 2] and
# VariableGridDy and VariableGridDx are both 40000, the outermost
# nest would have 100 grid cells in each direction with 40 km resolution,
# and there would be three levels of inner nesting, each at double the
# resolution of the previous nest, with the innermost nest having a grid
# cell length of 5 km.
Xnests= [18, 3, 2, 2, 2, 3, 2, 2]
Ynests= [14, 3, 2, 2, 2, 3, 2, 2]

# HiResLayers is the number of layers, starting at ground level, to do
# nesting in. Layers above this will have all grid cells in the lowest
# spatial resolution.
HiResLayers= 8

# GridProj gives projection info for the CTM grid in Proj4 or WKT format.
GridProj= "+proj=lcc +lat_1=33.000000 +lat_2=45.000000 +lat_0=40.000000 +lon_0=-97.000000 +x_0=0 +y_0=0 +a=6370997.000000 +b=6370997.000000 +to_meter=1"

# PopDensityThreshold is a limit for people per unit area in a grid cell
# (units will typically be either people / m^2 or people / degree^2,
# depending on the spatial projection of the model grid). If
# the population density in a grid cell is above this level, the cell in question
# is a candidate for splitting into smaller cells.
PopDensityThreshold= 0.0055

# PopThreshold is a limit for the total number of people in a grid cell.
# If the total population in a grid cell is above this level, the cell in question
# is a candidate for splitting into smaller cells.
PopThreshold= 40000.0

# PopConcThreshold is the limit for
# Σ(|ΔConcentration|)*combinedVolume*|ΔPopulation| / {Σ(|totalMass|)*totalPopulation}.
# See the documentation for PopConcMutator for more information.
PopConcThreshold= 0.000000001

# CensusFile is the path to the shapefile holding population information.
CensusFile= "${evaldata}/census2013blckgrp.shp"

# CensusPopColumns is a list of the data fields in CensusFile that should
# be included as population estimates in the model. They can be population
# of different demographics or for different population scenarios.
CensusPopColumns= ["TotalPop", "WhiteNoLat", "Black", "Native", "Asian", "Latino"]

# PopGridColumn is the name of the field in CensusFile that contains the data
# that should be compared to PopThreshold and PopDensityThreshold when determining
# if a grid cell should be split. It should typically be one of the fields
# in CensusPopColumns.
PopGridColumn= "TotalPop"

# MortalityRateFile is the path to the shapefile containing baseline
# mortality rate data.
MortalityRateFile= "${evaldata}/mortalityRates2013.shp"

# MortalityRateColumns maps the names of each input population group to the name
# of the field in MortalityRateFile that contains its respective baseline
# mortality rate, in units of deaths per year per 100,000 people. Only mortality
# rates used in output variable expressions need to be included here.
[VarGrid.MortalityRateColumns]
allcause = "TotalPop"
