InMAPData= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/inmapData_GEOSChem.ncf"

OutputFile= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/xxx.shp"

EmissionUnits= "tons/year"

[OutputVariables]
WindSpeed= "WindSpeed"


[VarGrid]
GridProj= "+proj=longlat"


[Preproc]
CTMType= "GEOS-Chem"

StartDate= "20130102"
EndDate= "20130104"
CtmGridXo= -2004000.0
CtmGridYo= -540000.0
CtmGridDx= 12000.0
CtmGridDy= 12000.0

[Preproc.GEOSChem]
GEOSA1= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/GEOSFP.[DATE].A1.2x25.nc"
GEOSA3Cld= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/GEOSFP.[DATE].A3cld.2x25.nc"
GEOSA3Dyn= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/GEOSFP.[DATE].A3dyn.2x25.nc"
GEOSI3= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/GEOSFP.[DATE].I3.2x25.nc"
GEOSA3MstE= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/GEOSFP.[DATE].A3mstE.2x25.nc"
GEOSChem= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/gc_output.[DATE].nc"
VegTypeGlobal= "${GOPATH}/src/github.com/spatialmodel/inmap/inmap/testdata/preproc/vegtype.global.txt"
Dash= true
